image: python:3.10-bullseye

stages:
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - archive/_build

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

jupyter-build:
  stage: build
  only:
    - main
  script:
    - pip install -r requirements.txt
    - jupyter-book build book/

push-html:
  stage: deploy
  only:
    - main
  before_script:
    - git fetch origin publish-html
    - git checkout publish-html
  script:
    - git status
