stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  REGISTRY_HOST: localhost:5000
  TAG_LATEST: $REGISTRY_HOST/$CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:latest
  TAG_DRAFT: $REGISTRY_HOST/$CI_PROJECT_NAME-draft/$CI_COMMIT_REF_NAME:latest
  GIT_SUBMODULE_STRATEGY: recursive # For submodules  

cache:
  paths:
    - .cache/pip

test-build:
  stage: test
  tags:
    - Textbook runner
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  script:
    - pip install -r requirements.txt
    - jupyter-book clean book/
    - jupyter-book build book/

build-book:
  stage: build
  tags:
    - Textbook runner
  rules:
    - if: $CI_COMMIT_BRANCH == "publish" && $CI_PIPELINE_SOURCE == "push"
      variables:
        TAG: $TAG_LATEST
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
      variables:
        TAG: $TAG_DRAFT
  script:
    - if [ "$TAG" = "$TAG_LATEST" ]; then sed --in-place=".bak" '/# START DRAFT/,/# END DRAFT/{//!d}' book/_config.yml; fi
    # You might need to adjust or remove these Docker commands depending on the runner's capabilities
    - docker build -t $TAG .
    - docker push $TAG

deploy-book:
  stage: deploy
  tags:
    - Textbook runner
  rules:
    - if: $CI_COMMIT_BRANCH == "publish" && $CI_PIPELINE_SOURCE == "push"
  script:
    # These Docker commands might need to be adjusted or replaced
    - docker stop $CI_PROJECT_NAME || true
    - docker rm $CI_PROJECT_NAME || true
    - docker run -d --restart always -p 8000:8000 --name $CI_PROJECT_NAME $TAG_LATEST
  environment:
    name: production
    url: https://interactivetextbooks.citg.tudelft.nl/jupyter-book-manual

deploy-draft:
  stage: deploy
  tags:
    - Textbook runner
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"
  script:
    # These Docker commands might need to be adjusted or replaced
    - docker stop $CI_PROJECT_NAME-draft || true
    - docker rm $CI_PROJECT_NAME-draft || true
    - docker run -d --restart always -p 8018:8000 --name $CI_PROJECT_NAME-draft $TAG_DRAFT
  environment:
    name: draft
    url: https://interactivetextbooks.citg.tudelft.nl/jupyter-book-manual-draft