title: Intro to Git, VS Code and Jupyter Books
author: Caspar Jungbacker
logo: images/TUDelft_logo_rgb.png

execute:
  execute_notebooks: auto

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - jupyterlite_sphinx
  config:
    jupyterlite_config:  jupyterlite-config.json
