title: Intro to Git, VS Code and Jupyter Books
author: Caspar Jungbacker
logo: images/TUDelft_logo_rgb.png

execute:
  execute_notebooks: 'off'

launch_buttons:
  thebe: true

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - jupyterlite_sphinx
  - sphinx.ext.imgconverter
  - download_link_replacer
  - jupyterbook_patches
  config:
    jupyterlite_config:  jupyterlite-config.json
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]