title: How to make a TeachBook
author: <a href="https://teachbooks.tudelft.nl/">TeachBooks Team</a>, built with <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt="">

logo: images/Logo_without_background.png

execute:
  execute_notebooks: 'off'

html:
  favicon : "images/favicon.ico"
  baseurl  : "https://teachbooks.tudelft.nl/jupyter-book-manual/"
# START DRAFT
  comments:
    hypothesis: true
# END DRAFT

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - jupyterlite_sphinx
  - sphinx.ext.imgconverter
  - download_link_replacer
  - jupyterbook_patches
  config:
    jupyterlite_config:  jupyterlite-config.json
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      repository_url: "https://gitlab.tudelft.nl/interactivetextbooks-citg/jupyter-book-manual"
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
          thebe: true
    html_show_copyright: false