title: How to make a TeachBook
author: <a href="https://teachbooks.tudelft.nl/">TeachBooks Team</a>, built with <a href="https://jupyterbook.org/">Jupyter Book</a>
logo: images/Logo_without_background.png
copyright: Delft University of Technology, CC BY 4.0

execute:
  execute_notebooks: 'off'

launch_buttons:
  thebe: true

html:
  favicon : "images/favicon.ico"

sphinx:
  extra_extensions:
  - sphinx_inline_tabs
  - jupyterlite_sphinx
  - sphinx.ext.imgconverter
  - download_link_replacer
  - jupyterbook_patches
  config:
    jupyterlite_config:  jupyterlite-config.json
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]

# START DRAFT
html:
  comments:
    hypothesis: true
# END DRAFT